### ISSUE TITLE
error arises when I install cupy via pip.

### ISSUE THREAD

**Issue by xlnwel** [musyoku/generative-query-network#7]
when I tried to install chainer and cupy via 'pip3 install chainer cupy h5py' , I received a error

>    Complete output from command python setup.py egg_info:
    Options: {'no_cuda': False, 'package_name': 'cupy', 'wheel_libs': [], 'no_rpath': False, 'linetrace': False, 'profile': False, 'long_description': None, 'annotate': False}
    **************************************************
    *** WARNING: nvcc not in path.
    *** WARNING: Please set path to nvcc.
    **************************************************
    
    -------- Configuring Module: cuda --------
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /tmp/tmpqasy3h8_/a.cpp:1:23: fatal error: cublas_v2.h: No such file or directory
    compilation terminated.
    command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************
    
    Build Environment:
      Include directories: []
      Library directories: []
      nvcc command       : (not found)
    
    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : (none)
      NVTOOLSEXT_PATH : (none)
      NVCC            : (none)
    
    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.
    
    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html
    
    ************************************************************
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tw6pfgs7/cupy/setup.py", line 64, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/tmp/pip-install-tw6pfgs7/cupy/cupy_setup_build.py", line 579, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/tmp/pip-install-tw6pfgs7/cupy/cupy_setup_build.py", line 378, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-tw6pfgs7/cupy/

what should i do with it?

**Comment by musyoku** [comment]
Please check if CUDA is installed.

**Comment by xlnwel** [comment]
Thanks, I'm afraid I cannot make it since I'm using a Mac :(

**Comment by musyoku** [comment]
Mac is not supported 😕
